
import "./globals.css";
//import  "bootstrap/dist/css/bootstrap.min.css"
//import "../styles/custom-bootstrap.scss";
import "@/app/styles/custom-bootstrap.scss"
import AddBootstrap from "./AddBootstrap";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AddBootstrap />
        {children}
      </body>
    </html>
  );
}
